"""Create link table

Revision ID: 1121962e64a
Revises:
Create Date: 2015-07-24 12:45:36.647061

"""

# revision identifiers, used by Alembic.
revision = '1121962e64a'
down_revision = None
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('dest', sa.Unicode(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    ### end Alembic commands ###
